### ISSUE TITLE
TypeError: a bytes-like object is required, not 'list'

### ISSUE THREAD

**Issue by machamy** [GitHub30/winocr#3]
`  File "\winocr.py", line 18, in recognize_pil
    return recognize_bytes(img.tobytes(), img.width, img.height, lang)
  File "\winocr.py", line 11, in recognize_bytes
    writer.write_bytes(list(bytes))`

I think something changed in DataWriter

**Comment by Ingnaryk** [comment]
pypi package wasn't updated yet?

**Comment by GitHub30** [comment]
I'll check it later

**Comment by GitHub30** [comment]
i have merged, thank you for your commit
